In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:



xs=torch.tensor([0,1,2,3,4,5,6,7.])
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])
i=7
x=xs[i]
y=ys[i]


In [3]:
def regression(my_m,my_x,my_b):
    return (my_m*my_x)+my_b

m = torch.tensor([0.9]).requires_grad_()
b = torch.tensor([0.1]).requires_grad_()
m,b

(tensor([0.9000], requires_grad=True), tensor([0.1000], requires_grad=True))

In [4]:
y_hat = regression(m,x,b)
y_hat

tensor([6.4000], grad_fn=<AddBackward0>)

In [5]:
def mse_single(my_yhat,my_y):
    return (my_yhat-my_y)**2

C = mse_single(y_hat,y)
C.backward()
m.grad,b.grad

(tensor([108.7800]), tensor([15.5400]))

In [6]:
2*x*(y_hat.item()-y)

tensor(108.7800)

In [7]:
2*(y_hat-y)

tensor([15.5400], grad_fn=<MulBackward0>)

### Gradient (nabla C )

list of all the del C / del model parameters with transpose applied to make them in a single column


nabla C = [del C / del p1 ,del C / del p2 , del C /del p3 ........del C / del pm].T 

In [8]:
gradient = torch.tensor([[b.grad.item(),m.grad.item()]]).T
gradient


tensor([[ 15.5400],
        [108.7800]])